apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ghost
spec:
  port:
    targetPort: https
  to:
    kind: Service
    name: ghost
    weight: 100
  wildcardPolicy: None
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect