kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app-data
  labels:
    app.kubernetes.io/name: demo-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"